
#ifndef __CWM_CMD_H
#define __CWM_CMD_H

typedef enum {    
    CWM_CMD_FAIL_SEND_TO_QUEUE = -100,
    CWM_CMD_FALL_SCREEN_NO_INITIAL = -1,
    CWM_CMD_NON = 0,
    CWM_CMD_SCREEN_INIT,
    CWM_CMD_SCREEN_ON,
    CWM_CMD_SCREEN_OFF,
    CWM_CMD_SCREEN_UPDATE,
    CWM_CMD_SCREEN_CLEAN,
    CWM_CMD_SCREEN_WRITE_AUTO_NEW_LINE,
    CWM_CMD_UART_LISTEN,
    CWM_CMD_UART_LISTEN_DISABLE,
    CWM_CMD_UART_LISTEN_RX_UPDATE
}uCWM_CMD;

#endif /* __CWM_CMD_H */
