
#ifndef __CWM_ERROR_CODE_H
#define __CWM_ERROR_CODE_H

#define CWM_ERROR_NULL_POINT -11
#define CWM_ERROR_MEMORY_ALLOC_FAIL -10
#define CWM_ERROR_ALREADY_INITIAL -3
#define CWM_ERROR_NOT_FOUND -2
#define CWM_ERROR -1

#define CWM_NON 0

#endif /* __CWM_ERROR_CODE_H */
